// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: idvlqdrbdswsquihfzey

class SupabaseConfig {
  static const String supabaseUrl = 'https://idvlqdrbdswsquihfzey.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkdmxxZHJiZHN3c3F1aWhmemV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5NTM4NDcsImV4cCI6MjA4MDUyOTg0N30.PHv26AVulkZ7dVN36h2p6IduHWk62G0az3nilF-7B9g';
}
